=== clojure-quant/fix-encoding/resources/fix-specs/xml-rapid/STANDARD/FIX.4.4/XML/Fields.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Fields" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Fields">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Tag" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="FieldName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Type" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Desc" minOccurs="0" od:jetType="memo" od:sqlSType="ntext">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="536870910"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LenRefers" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int"/>
<xsd:element name="AbbrName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="OverrideXMLName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="BaseCatagory" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="BaseCatagoryXMLName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="NotReqXML" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== clojure-quant/fix-encoding/specs/xml-rapid/STANDARD/FIX.4.1/XML/Fields.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Fields.xsd" generated="2006-05-08T17:42:55">
<Fields>
<Tag>1</Tag>
<FieldName>Account</FieldName>
<Type>char</Type>
<Desc>Account mnemonic as agreed between broker and institution.</Desc>
<LenRefers>0</LenRefers>
<AbbrName>Acct</AbbrName>
<OverrideXMLName>Acct</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>2</Tag>
<FieldName>AdvId</FieldName>
<Type>char</Type>
<Desc>Unique identifier of advertisement message.  (Prior to FIX 4.1 this field was of type int)</Desc>
<LenRefers>0</LenRefers>
<AbbrName>AdvId</AbbrName>
<OverrideXMLName>AdvId</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>3</Tag>
<FieldName>AdvRefID</FieldName>
<Type>char</Type>
<Desc>Reference identifier used with CANCEL and REPLACE transaction types.(Prior to FIX 4.1 this field was of type int)</Desc>
<LenRefers>0</LenRefers>
<AbbrName>AdvRefID</AbbrName>
<OverrideXMLName>AdvRefID</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>4</Tag>
<FieldName>AdvSide</FieldName>
<Type>char</Type>
<Desc>Broker&apos;s side of advertised tradeValid values: B = Buy S = SellX = CrossT = Trade</Desc>
<LenRefers>0</LenRefers>
<AbbrName>AdvSide</AbbrName>
<OverrideXMLName>AdvSide</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>5</Tag>
<FieldName>AdvTransType</FieldName>
<Type>char</Type>
<Desc>Identifies advertisement message transaction typeValid values:  N = NewC = CancelR = Replace </Desc>
<LenRefers>0</LenRefers>
<AbbrName>AdvTransTyp</AbbrName>
<OverrideXMLName>AdvTransTyp</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>6</Tag>
<FieldName>AvgPx</FieldName>
<Type>float</Type>
<Desc>Calculated average price of all fills on this order. Valid values:  0 - 99999999.9999 (number of decimal places may vary and not limited to four)</Desc>
<LenRefers>0</LenRefers>
<AbbrName>AvgPx</AbbrName>
<OverrideXMLName>AvgPx</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>7</Tag>
<FieldName>BeginSeqNo</FieldName>
<Type>int</Type>
<Desc>Message sequence number of first record in range to be resent</Desc>
<LenRefers>0</LenRefers>
<AbbrName>BeginSeqNo</AbbrName>
<OverrideXMLName>BeginSeqNo</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>8</Tag>
<FieldName>BeginString</FieldName>
<Type>char</Type>
<Desc>Identifies beginning of new message and protocol version.  ALWAYS FIRST FIELD IN MESSAGE. (Always unencrypted)Valid values:	FIX.4.1</Desc>
<LenRefers>0</LenRefers>
<AbbrName>BeginString</AbbrName>
<OverrideXMLName>BeginString</OverrideXMLName>
<NotReqXML>1</NotReqXML>
</Fields>
<Fields>
<Tag>9</Tag>
<FieldName>BodyLength</FieldName>
<Type>int</Type>
<Desc>Message length, in bytes, forward to the CheckSum field.  ALWAYS SECOND FIELD IN MESSAGE. (Always unencrypted)Valid values:   0 - 9999</Desc>
<LenRefers>0</LenRefers>
<AbbrName>BodyLength</AbbrName>
<OverrideXMLName>BodyLength</OverrideXMLName>
<NotReqXML>1</NotReqXML>
</Fields>
<Fields>
<Tag>10</Tag>
<FieldName>CheckSum</FieldName>
<Type>char</Type>
<Desc>Three byte, simple checksum  (see Appendix B for description).  ALWAYS LAST FIELD IN RECORD; i.e. serves, with the trailing &lt;SOH&gt;, as the end-of-record delimiter.  Always defined as three characters. (Always unencrypted)</Desc>
<LenRefers>0</LenRefers>
<AbbrName>CheckSum</AbbrName>
<OverrideXMLName>CheckSum</OverrideXMLName>
<NotReqXML>1</NotReqXML>
</Fields>
<Fields>
<Tag>11</Tag>
<FieldName>ClOrdID</FieldName>
<Type>char</Type>
<Desc>Unique identifier for Order as assigned by institution.  Uniqueness must be guaranteed within a single trading day.  Firms which electronically submit multi-day orders should consider embedding a date within the ClOrdID field to assure uniqueness across days.</Desc>
<LenRefers>0</LenRefers>
<AbbrName>ClOrdID</AbbrName>
<OverrideXMLName>ClOrdID</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>12</Tag>
<FieldName>Commission</FieldName>
<Type>float</Type>
<Desc>Commission.  Note if CommType is percentage, Commission of 5% should be represented as .05.</Desc>
<LenRefers>0</LenRefers>
<AbbrName>Comm</AbbrName>
<OverrideXMLName>Comm</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>13</Tag>
<FieldName>CommType</FieldName>
<Type>char</Type>
<Desc>Commission typeValid values:1	=	per share2 = percentage3 = absolute</Desc>
<LenRefers>0</LenRefers>
<AbbrName>CommTyp</AbbrName>
<OverrideXMLName>CommTyp</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>14</Tag>
<FieldName>CumQty</FieldName>
<Type>int</Type>
<Desc>Total number of shares filled.Valid values:(0 - 1000000000)</Desc>
<LenRefers>0</LenRefers>
<AbbrName>CumQty</AbbrName>
<OverrideXMLName>CumQty</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>15</Tag>
<FieldName>Currency</FieldName>
<Type>char</Type>
<Desc>Identifies currency used for price. Absence of this field is interpreted as the default for the security.  It is recommended that systems provide the currency value whenever possible.  See Appendix A for information on obtaining valid values. </Desc>
<LenRefers>0</LenRefers>
<AbbrName>Ccy</AbbrName>
<OverrideXMLName>Ccy</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>16</Tag>
<FieldName>EndSeqNo</FieldName>
<Type>int</Type>
<Desc>Message sequence number of last record in range to be resent.  If request is for a single record BeginSeqNo = EndSeqNo.  If request is for all messages subsequent to a particular message, EndSeqNo = &quot;999999&quot;</Desc>
<LenRefers>0</LenRefers>
<AbbrName>EndSeqNo</AbbrName>
<OverrideXMLName>EndSeqNo</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>17</Tag>
<FieldName>ExecID</FieldName>
<Type>char</Type>
<Desc>Unique identifier of execution message as assigned by broker (will be 0 (zero) for ExecTransType=3 (Status)).  Uniqueness must be guaranteed within a single trading day or the life of a multi-day order.  Firms which accept multi-day orders should consider embedding a date within the ExecID field to assure uniqueness across days.(Prior to FIX 4.1 this field was of type int)</Desc>
<LenRefers>0</LenRefers>
<AbbrName>ExecID</AbbrName>
<OverrideXMLName>ExecID</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>18</Tag>
<FieldName>ExecInst</FieldName>
<Type>char</Type>
<Desc>Instructions for order handling on exchange trading floor.  If more than one instruction is applicable to an order, this field can contain multiple instructions separated by space.Valid values:1 = Not held2 = Work3 = Go along4 = Over the day5 = Held6 = Participate don&apos;t initiate7 = Strict scale8 = Try to scale9 = Stay on bidside0 = Stay on offersideA = No cross (cross is forbidden)B = OK to crossC = Call firstD = Percent of volume “(indicates that the sender does not want to be all of the volume on the floor vs. a specific percentage)”E = Do not increase - DNIF = Do not reduce - DNRG = All or none - AONI = Institutions onlyL = Last peg (last sale)M = Mid-price peg (midprice of inside quote)N = Non-negotiableO = Opening peg
P = Market pegR = Primary peg (primary market - buy at bid/sell at offer)S = SuspendU = Customer Display Instruction (Rule11Ac1-1/4)V = Netting (for Forex)</Desc>
<LenRefers>0</LenRefers>
<AbbrName>ExecInst</AbbrName>
<OverrideXMLName>ExecInst</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>19</Tag>
<FieldName>ExecRefID</FieldName>
<Type>char</Type>
<Desc>Reference identifier used with Cancel and Correct transaction types.(Prior to FIX 4.1 this field was of type int)</Desc>
<LenRefers>0</LenRefers>
<AbbrName>ExecRefID</AbbrName>
<OverrideXMLName>ExecRefID</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>20</Tag>
<FieldName>ExecTransType</FieldName>
<Type>char</Type>
<Desc>Identifies transaction typeValid values:  0 = New 1 = Cancel2 = Correct3 = Status</Desc>
<LenRefers>0</LenRefers>
<AbbrName>ExecTransTyp</AbbrName>
<OverrideXMLName>ExecTransTyp</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>21</Tag>
<FieldName>HandlInst</FieldName>
<Type>char</Type>
<Desc>Instructions for order handling on Broker trading floorValid values:1 = Automated execution order, private, no Broker intervention2 = Automated execution order, public, Broker intervention OK3 = Manual order, best execution</Desc>
<LenRefers>0</LenRefers>
<AbbrName>HandlInst</AbbrName>
<OverrideXMLName>HandlInst</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>22</Tag>
<FieldName>SecurityIDSource</FieldName>
<Type>char</Type>
<Desc>Identifies class of alternative SecurityIDValid values:1 = CUSIP2 = SEDOL3 = QUIK4 = ISIN number5 = RIC code6 = ISO Currency Code7 = ISO Country Code100+ are reserved for private security identifications</Desc>
<LenRefers>0</LenRefers>
<AbbrName>IDSrc</AbbrName>
<OverrideXMLName>IDSrc</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>23</Tag>
<FieldName>IOIID</FieldName>
<Type>char</Type>
<Desc>Unique identifier of IOI message.(Prior to FIX 4.1 this field was of type int)</Desc>
<LenRefers>0</LenRefers>
<AbbrName>IOIID</AbbrName>
<OverrideXMLName>IOIID</OverrideXMLName>
<NotReqXML>0</NotReqXML>
</Fields>
<Fields>
<Tag>24</Tag>
<FieldName>IOIOthSvc</FieldName>
<Type>char</Type>
<Desc>Indicates if, and on which other services, the indication has been advertised.  Each character represents an additional service (e.g. if on Bridge and Autex, field = BA, if only on Autex, field = A)Valid values:A	=	AutexB	=	Bridge</Desc>
